import { promises as fs } from "node:fs";
import path from "node:path";
import { Logger } from "../utils/logger.js";
import { BASE_DIR, getErrorMessage } from "../utils/index.js";
import type {
  BuddyId,
  BuddyProfile,
  BuddySummary,
  BuddyStorage,
  MemoryEntry,
} from "./types.js";
import { validateBuddyExport } from "./types.js";

const BUDDY_DIR = path.join(BASE_DIR, "buddy");
const logger = new Logger("buddy-storage");

function isBuddyBackupData(data: unknown): data is {
  id: string;
  username: string;
  soul: string;
  user: string;
  memory: string;
  sourceRepos: string[];
  createdAt: string;
  updatedAt: string;
} {
  if (typeof data !== "object" || data === null) return false;
  const obj = data as Record<string, unknown>;
  return (
    typeof obj.id === "string" &&
    typeof obj.username === "string" &&
    typeof obj.soul === "string" &&
    typeof obj.user === "string" &&
    typeof obj.memory === "string" &&
    Array.isArray(obj.sourceRepos) &&
    obj.sourceRepos.every((s) => typeof s === "string") &&
    typeof obj.createdAt === "string" &&
    typeof obj.updatedAt === "string"
  );
}

const SOUL_TEMPLATE = `# Review Philosophy
(Generated by agent-buddy - review philosophy will be populated after analysis)

## Priorities
(To be analyzed)

## Communication Style
(To be analyzed)
`;

const USER_TEMPLATE = `# Profile
(Generated by agent-buddy - profile will be populated after analysis)

## Expertise
(To be analyzed)

## Stats
(To be analyzed)
`;

const MEMORY_TEMPLATE = `# Memory Index
(Generated by agent-buddy - memory entries will be added after analysis)
`;

export class BuddyFileSystemStorage implements BuddyStorage {
  private buddyDir: string;

  constructor(baseDir?: string) {
    this.buddyDir = baseDir ? path.join(baseDir, "buddy") : BUDDY_DIR;
  }

  async init(): Promise<void> {
    await fs.mkdir(this.buddyDir, { recursive: true });
  }

  async readProfile(id: BuddyId): Promise<BuddyProfile | null> {
    const dir = this.buddyDirPath(id);
    try {
      const [soul, user, memory] = await Promise.all([
        fs.readFile(path.join(dir, "SOUL.md"), "utf-8").catch(() => SOUL_TEMPLATE),
        fs.readFile(path.join(dir, "USER.md"), "utf-8").catch(() => USER_TEMPLATE),
        fs.readFile(path.join(dir, "MEMORY.md"), "utf-8").catch(() => MEMORY_TEMPLATE),
      ]);

      const stat = await fs.stat(dir);

      // Try to read metadata.json for username and sourceRepos
      let username = id;
      let sourceRepos: string[] = [];
      let createdAt = stat.birthtime;
      let updatedAt = stat.mtime;
      let reviewCount = 0;
      let lastReviewAt: Date | undefined;

      const metadata = await this.readMetadata(dir);
      if (metadata.username) username = metadata.username as string;
      if (metadata.sourceRepos) sourceRepos = metadata.sourceRepos as string[];
      if (metadata.createdAt) createdAt = new Date(metadata.createdAt as string);
      if (metadata.updatedAt) updatedAt = new Date(metadata.updatedAt as string);
      if (metadata.reviewCount) reviewCount = metadata.reviewCount as number;
      if (metadata.lastReviewAt) lastReviewAt = new Date(metadata.lastReviewAt as string);

      return {
        id,
        username,
        soul,
        user,
        memory,
        sourceRepos,
        createdAt,
        updatedAt,
        reviewCount,
        lastReviewAt,
      };
    } catch (err) {
      logger.warn("Failed to read profile", { id, error: getErrorMessage(err) });
      return null;
    }
  }

  async writeProfile(id: BuddyId, profile: BuddyProfile): Promise<void> {
    const dir = this.buddyDirPath(id);
    await fs.mkdir(dir, { recursive: true });
    await fs.mkdir(path.join(dir, "memory"), { recursive: true });

    // Create version backup before overwriting
    await this.createVersionBackup(id, profile);

    // Save metadata.json with username and sourceRepos
    const metadata = {
      id: profile.id,
      username: profile.username,
      sourceRepos: profile.sourceRepos,
      createdAt: profile.createdAt.toISOString(),
      updatedAt: profile.updatedAt.toISOString(),
      reviewCount: profile.reviewCount || 0,
      lastReviewAt: profile.lastReviewAt ? profile.lastReviewAt.toISOString() : undefined,
    };

    await Promise.all([
      fs.writeFile(path.join(dir, "SOUL.md"), profile.soul),
      fs.writeFile(path.join(dir, "USER.md"), profile.user),
      fs.writeFile(path.join(dir, "MEMORY.md"), profile.memory),
      fs.writeFile(path.join(dir, "metadata.json"), JSON.stringify(metadata, null, 2)),
    ]);
  }

  async listBuddies(): Promise<BuddySummary[]> {
    try {
      const entries = await fs.readdir(this.buddyDir, { withFileTypes: true });
      const buddyDirs = entries.filter((e) => e.isDirectory());

      const summaries = await Promise.all(
        buddyDirs.map(async (dir) => {
          const id = dir.name;
          const profile = await this.readProfile(id);
          if (!profile) return null;

          return {
            id,
            username: profile.username,
            sourceRepos: profile.sourceRepos,
            totalReviews: profile.reviewCount || 0,
            lastUpdated: profile.updatedAt,
          };
        })
      );

      return summaries.filter((s): s is BuddySummary => s !== null);
    } catch (err) {
      logger.error("Failed to list buddies", { error: getErrorMessage(err) });
      return [];
    }
  }

  async deleteBuddy(id: BuddyId): Promise<void> {
    const dir = this.buddyDirPath(id);
    await fs.rm(dir, { recursive: true, force: true });
  }

  async incrementReviewCount(id: BuddyId): Promise<void> {
    const dir = this.buddyDirPath(id);
    const metadataPath = path.join(dir, "metadata.json");

    const metadata = await this.readMetadata(dir);
    metadata.reviewCount = ((metadata.reviewCount as number) || 0) + 1;
    metadata.lastReviewAt = new Date().toISOString();
    await fs.writeFile(metadataPath, JSON.stringify(metadata, null, 2));
  }

  async addMemoryEntry(entry: MemoryEntry): Promise<void> {
    const memoryDir = path.join(this.buddyDirPath(entry.buddyId), "memory");
    await fs.mkdir(memoryDir, { recursive: true });

    const filename = `${entry.org}-${entry.repo}-pr-${entry.prNumber}.md`;
    const content = this.formatMemoryEntry(entry);
    await fs.writeFile(path.join(memoryDir, filename), content);

    await this.regenerateMemoryMd(entry.buddyId);
  }

  async listMemoryEntries(buddyId: BuddyId): Promise<MemoryEntry[]> {
    const memoryDir = path.join(this.buddyDirPath(buddyId), "memory");
    try {
      const files = await fs.readdir(memoryDir);
      const entries: MemoryEntry[] = [];

      for (const file of files) {
        if (!file.endsWith(".md")) continue;
        const content = await fs.readFile(path.join(memoryDir, file), "utf-8");
        const parsed = this.parseMemoryFile(file, content, buddyId);
        if (parsed) entries.push(parsed);
      }

      return entries.sort(
        (a, b) => b.createdAt.getTime() - a.createdAt.getTime()
      );
    } catch (err) {
      logger.warn("Failed to list memory entries", { buddyId, error: getErrorMessage(err) });
      return [];
    }
  }

  async searchBuddies(query: string): Promise<BuddySummary[]> {
    const all = await this.listBuddies();
    const lowerQuery = query.toLowerCase();
    return all.filter(
      (b) =>
        b.username.toLowerCase().includes(lowerQuery) ||
        b.sourceRepos.some((r) => r.toLowerCase().includes(lowerQuery))
    );
  }

  async exportBuddy(id: BuddyId): Promise<Buffer> {
    const dir = this.buddyDirPath(id);
    const profile = await this.readProfile(id);
    if (!profile) throw new Error(`Buddy ${id} not found`);

    const { spawn } = await import("node:child_process");
    return new Promise((resolve, reject) => {
      const chunks: Buffer[] = [];
      const child = spawn("tar", ["czf", "-", "."], {
        cwd: dir,
        stdio: ["ignore", "pipe", "pipe"],
      });
      child.stdout.on("data", (chunk: Buffer) => chunks.push(chunk));
      child.stderr.on("data", (chunk: Buffer) => chunks.push(chunk));
      child.on("error", reject);
      child.on("close", (code) => {
        if (code === 0) {
          resolve(Buffer.concat(chunks));
        } else {
          reject(new Error(`tar exited with code ${code}`));
        }
      });
    });
  }

  async exportProfile(buddyId: string): Promise<string> {
    const profile = await this.readProfile(buddyId);
    if (!profile) throw new Error(`Buddy ${buddyId} not found`);

    const exportData = {
      id: profile.id,
      username: profile.username,
      soul: profile.soul,
      user: profile.user,
      memory: profile.memory,
      sourceRepos: profile.sourceRepos,
      exportedAt: new Date().toISOString(),
      version: "1.0",
    };

    return JSON.stringify(exportData, null, 2);
  }

  async importProfile(json: string, newId?: string): Promise<string> {
    let data: unknown;
    try {
      data = JSON.parse(json);
    } catch (err) {
      throw new Error(`Invalid JSON: unable to parse input (${getErrorMessage(err)})`);
    }

    // Validate the export structure
    const validation = validateBuddyExport(data);
    if (!validation.valid) {
      const errorMessages = validation.errors.map((e) => `  - ${e.field}: ${e.message}`).join("\n");
      throw new Error(`Invalid buddy export:\n${errorMessages}`);
    }

    // Log version warning if present
    if (validation.versionWarning) {
      logger.warn(validation.versionWarning);
    }

    const exportData = data as {
      id: string;
      username: string;
      soul: string;
      user: string;
      memory: string;
      sourceRepos: string[];
      version: string;
      exportedAt: string;
    };

    const targetId = newId || exportData.id;

    const profile: BuddyProfile = {
      id: targetId,
      username: exportData.username || targetId,
      soul: exportData.soul,
      user: exportData.user,
      memory: exportData.memory,
      sourceRepos: exportData.sourceRepos || [],
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    await this.writeProfile(targetId, profile);
    return targetId;
  }

  private async listVersionFiles(versionsDir: string): Promise<string[]> {
    try {
      const files = await fs.readdir(versionsDir);
      return files.filter((f) => f.startsWith("profile.v") && f.endsWith(".json"));
    } catch {
      return [];
    }
  }

  private async readMetadata(dir: string): Promise<Record<string, unknown>> {
    try {
      const raw = await fs.readFile(path.join(dir, "metadata.json"), "utf-8");
      return JSON.parse(raw) as Record<string, unknown>;
    } catch {
      return {};
    }
  }

  private buddyDirPath(id: BuddyId): string {
    if (!/^[a-zA-Z0-9][a-zA-Z0-9._-]*$/.test(id)) {
      throw new Error(`Invalid buddy ID: "${id}" — only alphanumeric characters, dots, hyphens, and underscores are allowed`);
    }
    const resolved = path.resolve(this.buddyDir, id);
    if (!resolved.startsWith(path.resolve(this.buddyDir) + path.sep) && resolved !== path.resolve(this.buddyDir)) {
      throw new Error(`Invalid buddy ID: path traversal detected`);
    }
    return resolved;
  }

  private formatMemoryEntry(entry: MemoryEntry): string {
    const lines: string[] = [
      `# ${entry.org}/${entry.repo} - PR #${entry.prNumber}`,
    ];

    if (entry.prTitle) {
      lines.push(`**Title:** ${entry.prTitle}`);
    }

    lines.push(`**Date:** ${entry.createdAt.toISOString()}`, "");

    if (entry.keyLearnings.length > 0) {
      lines.push("## Key Learnings", "");
      for (const learning of entry.keyLearnings) {
        lines.push(`- ${learning}`);
      }
      lines.push("");
    }

    if (entry.content) {
      lines.push("## Review Summary", "");
      lines.push(entry.content);
    }

    return lines.join("\n");
  }

  private parseMemoryFile(
    filename: string,
    content: string,
    buddyId: BuddyId
  ): MemoryEntry | null {
    const match = filename.match(/^([^-]+)-([^-]+)-pr-(\d+)\.md$/);
    if (!match) return null;

    const keyLearnings: string[] = [];
    const learningMatch = content.match(
      /## Key Learnings\n\n((?:- [^\n]+\n?)+)/
    );
    if (learningMatch) {
      for (const line of learningMatch[1].split("\n")) {
        const cleaned = line.replace(/^-\s*/, "").trim();
        if (cleaned) keyLearnings.push(cleaned);
      }
    }

    // Extract PR title if present
    const prTitleMatch = content.match(/\*\*Title:\*\*([^\n]+)/);
    const prTitle = prTitleMatch ? prTitleMatch[1].trim() : undefined;

    // Extract date if present
    const dateMatch = content.match(/\*\*Date:\*\*([^\n]+)/);
    const createdAt = dateMatch ? new Date(dateMatch[1].trim()) : new Date();

    // Extract review summary content
    let reviewContent = "";
    const summaryMatch = content.match(/## Review Summary\n\n([\s\S]+)/);
    if (summaryMatch) {
      reviewContent = summaryMatch[1].trim();
    }

    return {
      buddyId,
      org: match[1],
      repo: match[2],
      prNumber: parseInt(match[3], 10),
      prTitle,
      content: reviewContent,
      keyLearnings,
      createdAt,
    };
  }

  private async createVersionBackup(id: BuddyId, profile: BuddyProfile): Promise<void> {
    const dir = this.buddyDirPath(id);
    const versionsDir = path.join(dir, "versions");
    await fs.mkdir(versionsDir, { recursive: true });

    // Get existing version files
    const existingVersions = await this.listVersionFiles(versionsDir);
    const version = existingVersions.length;

    const versionFile = path.join(versionsDir, `profile.v${version}.json`);
    const backupData = {
      id: profile.id,
      username: profile.username,
      soul: profile.soul,
      user: profile.user,
      memory: profile.memory,
      sourceRepos: profile.sourceRepos,
      createdAt: profile.createdAt,
      updatedAt: profile.updatedAt,
      backedUpAt: new Date().toISOString(),
      version,
    };

    await fs.writeFile(versionFile, JSON.stringify(backupData, null, 2));

    // Keep only the last 5 versions
    const allVersions = await this.listVersionFiles(versionsDir);
    if (allVersions.length > 5) {
      allVersions.sort();
      const toDelete = allVersions.slice(0, allVersions.length - 5);
      for (const file of toDelete) {
        await fs.unlink(path.join(versionsDir, file));
      }
    }
  }

  async rollbackProfile(id: BuddyId, version?: number): Promise<BuddyProfile> {
    const dir = this.buddyDirPath(id);
    const versionsDir = path.join(dir, "versions");

    // Read available versions
    const versionFiles = await this.listVersionFiles(versionsDir);
    if (versionFiles.length === 0) {
      throw new Error(`No version backups found for buddy ${id}`);
    }

    // Determine which version to restore
    let targetVersion: number;
    if (version !== undefined) {
      targetVersion = version;
    } else {
      // Use the latest version
      const versions = versionFiles.map((f) => parseInt(f.match(/profile\.v(\d+)\.json/)?.[1] || "0", 10));
      targetVersion = Math.max(...versions);
    }

    const versionFile = path.join(versionsDir, `profile.v${targetVersion}.json`);

    try {
      const content = await fs.readFile(versionFile, "utf-8");
      const backupData = JSON.parse(content);

      if (!isBuddyBackupData(backupData)) {
        throw new Error("Invalid backup data: missing required profile fields");
      }

      const restoredProfile: BuddyProfile = {
        id: backupData.id,
        username: backupData.username,
        soul: backupData.soul,
        user: backupData.user,
        memory: backupData.memory,
        sourceRepos: backupData.sourceRepos,
        createdAt: new Date(backupData.createdAt),
        updatedAt: new Date(backupData.updatedAt),
      };

      // Write the restored profile
      await this.writeProfile(id, restoredProfile);

      return restoredProfile;
    } catch (err) {
      const message = getErrorMessage(err);
      throw new Error(`Failed to rollback to version ${targetVersion}: ${message}`);
    }
  }

  async listProfileVersions(id: BuddyId): Promise<Array<{ version: number; backedUpAt: string }>> {
    const versionsDir = path.join(this.buddyDirPath(id), "versions");

    try {
      const versionFiles = await this.listVersionFiles(versionsDir);

      const versions = await Promise.all(
        versionFiles.map(async (f) => {
          const match = f.match(/profile\.v(\d+)\.json/);
          if (!match) return null;

          const version = parseInt(match[1], 10);
          const content = await fs.readFile(path.join(versionsDir, f), "utf-8");
          const backupData = JSON.parse(content);

          if (typeof backupData?.backedUpAt !== "string") return null;

          return {
            version,
            backedUpAt: backupData.backedUpAt,
          };
        })
      );

      return versions.filter((v): v is { version: number; backedUpAt: string } => v !== null);
    } catch (err) {
      logger.warn("Failed to list profile versions", { id, error: getErrorMessage(err) });
      return [];
    }
  }

  async regenerateMemoryMd(buddyId: BuddyId): Promise<void> {
    const entries = await this.listMemoryEntries(buddyId);
    const memoryIndexPath = path.join(this.buddyDirPath(buddyId), "MEMORY.md");

    if (entries.length === 0) {
      await fs.writeFile(memoryIndexPath, MEMORY_TEMPLATE);
      return;
    }

    // Aggregate patterns across all entries
    const allKeyLearnings = new Set<string>();
    const repos = new Set<string>();
    const prCounts = new Map<string, number>();

    for (const entry of entries) {
      for (const learning of entry.keyLearnings) {
        allKeyLearnings.add(learning);
      }
      repos.add(`${entry.org}/${entry.repo}`);
      const repoKey = `${entry.org}/${entry.repo}`;
      prCounts.set(repoKey, (prCounts.get(repoKey) || 0) + 1);
    }

    // Generate MEMORY.md content
    const lines = [
      "# Memory Index",
      "",
      `Generated on ${new Date().toISOString()}`,
      "",
      "## Summary",
      "",
      `- Total Reviews: ${entries.length}`,
      `- Repositories Reviewed: ${repos.size}`,
      `- Key Patterns Identified: ${allKeyLearnings.size}`,
      "",
    ];

    if (allKeyLearnings.size > 0) {
      lines.push("## Key Patterns", "");
      for (const learning of Array.from(allKeyLearnings).sort()) {
        lines.push(`- ${learning}`);
      }
      lines.push("");
    }

    lines.push("## Memory Entries", "");
    for (const entry of entries.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())) {
      const filename = `${entry.org}-${entry.repo}-pr-${entry.prNumber}.md`;
      const title = entry.prTitle ? `: ${entry.prTitle}` : "";
      lines.push(`- [${entry.org}/${entry.repo} PR #${entry.prNumber}${title}](memory/${filename}) - ${entry.createdAt.toISOString()}`);
    }
    lines.push("");

    await fs.writeFile(memoryIndexPath, lines.join("\n"));
  }
}
